name: Pipeline Setup Testing

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H 157.245.86.84 > ~/.ssh/known_hosts
      
    - name: Deploy to server 
      run: ssh -tt -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no root@157.245.86.84
      
    - name: Deploy
      run:
        cd /root/mohid/invozone
        mkdir test
