name: Create Folder Pipeline

on:
  push:
    branches:
      - main

jobs:
  create_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH
      run:
         mkdir -p ~/
         echo SSH_PRIVATE_KEY > ~/id_rsa
         chmod 600 ~/id_rsa
         ssh-keyscan 157.245.86.84 >> ~/known_hosts



    - name: Connect to server
      run: ssh -tt root@157.245.86.84 'mkdir /root/mohid'

    - name: Commit and push changes
      run: |
        git config --global user.name 'maatique'
        git config --global user.email 'mohid.ali@invozone.com'
        git add .
        git commit -m 'Create folder'
        git push
