name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: SSH to server and Deploy App
      uses: appleboy/ssh-action@master
      with:
          host: 
           157.245.86.84
          username: root 
          key: SSH_PRIVATE_KEY
          port: 
            22
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
