name: Connect to Server

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
   
   
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH
        run: sudo apt-get install openssh-client
      
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
         host:
           174.138.34.138
         username:
           mohid
         key:
           ${{ secrets.SSH_PRIVATE_KEY }}
         port:
           22
      
      - name: clone repo
        run: |
            cd  ~/mohid
            git clone https://github.com/maatique/invozone.git
