
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-do:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ 157.245.86.84 }}
          username: ${{ root }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ 22 }}
          script: |
            cd ~/app
            git pull origin master
            npm run build
            pm2 restart next
