
name: Pipeline Setup Testing

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
       - name: executing remote ssh commands using password
         uses: appleboy/ssh-action@v0.1.10
         with:
          host: ${{ 157.245.86.84 }}
          username: ${{ root }}
          password: ${{ aLi123ali }}
          port: ${{ 22 }}
          
       - name: Deploy
          run:
            cd /root/mohid/invozone
             mkdir test
